name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      #from Django settings y;all
      TIME_ZONE: "Africa/Lagos"
      DJANGO_SETTINGS_MODULE: zeecommerce.settings.dev
      DEBUG: "False"

      #CI-safe secrets/config (Remember to never use prod secrets here, fellow devs!)
      SECRET_KEY: "ci-insecure-secret-key"
      DATABASE_URL: "sqlite:///db.sqlite3"

      #Dummy Redis URL
      REDIS_URL: "redis://127.0.0.1:6379/0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django system checks
        run: |
           python manage.py check

      - name: Run tests
        run: |
           python manage.py test
