# Generated by Django 5.2.10 on 2026-02-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='products_ca_slug_da4386_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'), models.Index(fields=['category', 'price'], name='products_pr_categor_47b724_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_gte_0'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_stock_gte_0')],
            },
        ),
    ]
