# Generated by Django 5.2.10 on 2026-02-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_stock_gte_0',
        ),
    ]
